"""
Django settings for isi_payslip_email project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '26m$o*!y6r9f8k%*h391r@2s-m+2)pf5t2mhm=i=wsmexz=(b3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/site_media/media/"

# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'constance',
    'constance.backends.database',
    'payslip',
    'webapp'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'isi_payslip_email.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'constance.context_processors.config',
            ],
        },
    },
]

WSGI_APPLICATION = 'isi_payslip_email.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "isi_payslip_email",
        "USER": "root",                      # Not used with sqlite3.
        "PASSWORD": "",
        "HOST": "localhost",
        "TEST_CHARSET" : "utf8",
        "TEST_COLLATION": "utf8_general_ci"
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


COMPANY_EMAIL = "inovouze@gmail.com"

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/payslip'
LOGOUT_REDIRECT_URL = '/'

STATIC_URL = '/static/'

# Email Server Settings. Change as needed
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'isipslip@gmail.com'
EMAIL_HOST_PASSWORD = 'isi123456'
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

COMPANY_EMAIL = "innovouze@gmail.com"

PAYSLIP_PATH_SEPARATOR = "Payslip -"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler'
        }
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        }
    }
}

# django-constance
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True
CONSTANCE_CONFIG = {
    'COMPANY': ('Innovuze Solutions, Inc.', ''),
    'COMPANY_ADDRESS': ("""8th Level, Gateway Tower,
                           Limketkai Center, Lapasan,
                           Cagayan de Oro City""", ''),
    'COMPANY_SITE': ('http://www.innovuze.com',''),
    'COMPANY_PHONE': ('(088) 324-0454', 'Company contact.'),
    'COMPANY_EMAIL': ('innovouze@gmail.com', 'Company Email'),
    'PAYSLIP_PATH_SEPARATOR': (PAYSLIP_PATH_SEPARATOR, 'Payslip Path Separator'),
    'EMAIL_TEMPLATE_DISCLAIMER': ("""This a system generated email that may contain confidential information for the sole use of the intended recipient/s.
        If you are not the intended recipient, please contact the sender, delete this email and maintain the confidentiality of what you may have read.
        """, 'Email disclaimer message.'),
    'EMAIL_COMPANY_LOGO': ('http://oi58.tinypic.com/az8468.jpg', 'Company logo url.'),
    'EMAIL_GREETINGS': ('Greetings, {employee_name}!', 'You can use the {{ employee_name}} and {{payslip_name}} tags here.'),
    'EMAIL_BODY_MESSAGES': ("""Attached is your pay slip for the following duration: {payslip_name}
                            \nThank you and have a good day.""", 'You can use {{ employee_name}} and {{payslip_name}} tags.')

}
CONSTANCE_SUPERUSER_ONLY = True
CONSTANCE_DATABASE_PREFIX = 'constance:payslip_email:'